# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bazaar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Firebase/Core'
        pod 'Firebase/Analytics'
        pod 'Firebase/Auth'
        pod 'Firebase/Firestore'
        pod 'Firebase/Storage'
        pod 'Firebase/Database'
        pod 'FirebaseUI'

  # Pods for Bazaar

  target 'BazaarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BazaarUITests' do
    # Pods for testing
  end

end
